# Project Proposal

**by: Victoria Gemoets-Johnson, Elijah Gilbert, Anna Havner**

In [2]:
import pandas as pd

In [3]:
pvd = pd.read_excel('data/pvdstudy.xlsx')
pvd

,L.P.,Participant code,Pregnancy meeting,Stress scale,Stress1,Stress2,Stress3,Stress4,Stress5,Stress6,...,PVD9.1,PVD10.1,PVD11.1,PVD12.1,PVD13.1,PVD14.1,PVD15.1,Infectability sum,Germ aversion Sum,Total Sum
0,1,1,NaN,NaN,2,2,3,2,1,3,...,1,1,7,6,3,6,4,14,22,36
1,2,2,NaN,NaN,3,4,4,2,3,4,...,2,6,6,3,1,3,2,34,30,64
2,3,3,NaN,NaN,1,1,1,1,1,1,...,1,1,7,1,1,7,7,13,28,41
3,4,4,NaN,NaN,4,1,4,0,1,2,...,1,1,3,4,3,4,1,17,22,39
4,5,5,NaN,NaN,3,1,4,2,2,4,...,3,4,1,3,7,4,2,29,33,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,217,NaN,NaN,1,1,2,1,1,3,...,1,1,5,6,3,6,1,14,19,33
196,197,218,NaN,NaN,1,0,2,2,2,3,...,4,4,6,4,3,4,3,29,34,63
197,198,219,NaN,NaN,2,2,2,1,1,3,...,3,1,6,6,5,5,1,14,23,37
198,199,220,NaN,NaN,0,0,0,0,0,0,...,1,4,5,4,2,4,2,28,32,60
199,200,221,NaN,NaN,1,1,2,0,0,1,...,2,2,4,5,5,5,3,18,29,47

In [4]:
hrsn = pd.read_csv('data/hrsnstudy.csv')
hrsn

,study_id,delivery_type,survey_language,year_del,month_postpartum,age,hispanic,raceth_grp,birth_country,insurance,...,count_total_need_plus_tp2,flag_any_plus_tp2,received,daycount,lastday,htn,pp_visit_6_wks,pcp,ed_or_hosp,random_order
0,1,C/S,Haitian Creole,2022,23,44,2,2,2,1,...,3,1,1,3.0,26.0,No,1,0,0,0.007992
1,2,C/S,English,2022,24,33,2,2,1,1,...,2,1,0,NaN,NaN,NaN,0,0,0,0.014961
2,3,C/S,Spanish,2022,17,22,1,1,2,1,...,2,1,1,14.0,40.0,Stage 1,1,1,0,0.017957
3,4,C/S,Haitian Creole,2023,6,40,2,2,2,1,...,2,1,0,NaN,NaN,NaN,1,0,0,0.018918
4,5,Vag,English,2023,10,35,2,2,1,1,...,2,1,1,3.0,25.0,Stage 1,1,1,0,0.030806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,81,C/S,English,2022,22,31,2,4,2,2,...,0,0,1,33.0,41.0,Stage 2+,1,0,0,0.959896
81,82,Vag,English,2023,14,33,2,3,1,2,...,0,0,0,NaN,NaN,NaN,1,0,0,0.975410
82,83,Vag,English,2022,22,40,1,1,1,1,...,1,1,1,1.0,10.0,NaN,1,0,1,0.984596
83,84,Vag,Haitian Creole,2022,14,33,2,2,2,1,...,4,1,1,37.0,42.0,Stage 2+,1,1,0,0.985341
84,85,C/S,English,2022,20,21,2,2,2,1,...,4,1,1,27.0,39.0,Stage 2+,1,1,0,0.985633

**Data Summary**

We are working with two data sets, one that focuses on hypertension and postpartum and one that centers on disease aversion and pregnancy. We found these public data sets on the provided OSF website. 
The "Disease Aversion and Pregnancy" data set (PVD), was collected by
The "Hypertension and Postpartum" data set (HRSN), was collected by

Each row represents on individual person. 
The variables we are planning to use out of the PVD data set are 
The variables we are planning to use out of the HRSN data set are

***

**Question 1**

Anna - write the question here

In [8]:
# code the first look figure here

Add plan and expected outcomes here

***

**Question 2**

Elijah - write the question here

In [11]:
# code the first look figure here

Add plan and expected outcomes here

***

**Question 3**

Victoria - write the question here

In [ ]:
# code the first look figure here

Add plan and expected outcomes here

***